routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', 'Dashboard\LogsController@index')->name('admin.login');
Route::post('admin/login', 'Dashboard\LogsController@store')->name('admin.login');

Route::group(['middleware'=>'admin'], function(){

    Route::resource('dashboard/comment/replies','Dashboard\CommentRepliesController');
    Route::resource('dashboard/comments',       'Dashboard\CommentsController');
    Route::resource('dashboard/media',          'Dashboard\MediasController');
    Route::resource('dashboard/categories',     'Dashboard\CategoriesController');
    Route::resource('dashboard/posts',          'Dashboard\PostsController');
    Route::resource('dashboard/users',          'Dashboard\UsersController');
    Route::resource('dashboard/admin',          'Dashboard\AdminController');
    Route::resource('dashboard',                'Dashboard\DashboardController');
    Route::post('dashboard/logout', 'Dashboard\LoginController@logout')->name('admin.logout');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $fillable = ['name'];
}

app/Http/Controllers/Dashboard/CategoriesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categories = Category::all();

        return view('dashboard.sections.categories.index', compact('categories'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        Category::create($request->all());

        return redirect('dashboard/categories');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $category = Category::findOrFail($id);

        return view('dashboard.sections.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $category = Category::findOrFail($id);

        $category->update($request->all());

        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $category = Category::findOrFail($id);

        $category->delete();

        return redirect()->route('categories.index');
    }
}

resources/views/dashboard/sections/categories/edit.blade.php
@extends('dashboard.layouts.app')

@section('title', 'D3awa/Edit Categories')

@section('content')

    <div class=" col-md-10 float-right  col px-5 pl-md-2 pt-2 main">

        <div class="add">

            <h5>Categories</h5>

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{{route('dashboard.index')}}">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{{route('categories.index')}}">Categories</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Edit {{$category->name}}</li>
                </ol>
            </nav>
        </div>
        <!-- add -->
        <div class="parent">



            {!! Form::model($category, ['method'=>'PATCH', 'action'=>['Dashboard\CategoriesController@update', $category->id]]) !!}
            <div class="form-group">
                {!! Form::label('name', 'Name:') !!}
                {!! Form::text('name', null, ['class'=>'form-control']) !!}
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        {!! Form::submit('Update Category', ['class'=>'btn btn-primary col-md-12']) !!}
                    </div>
                    {!! Form::close() !!}

                </div>
                <div class="col-md-6">


                    {!! Form::open(['method'=>'DELETE', 'action'=>['Dashboard\CategoriesController@destroy', $category->id]]) !!}
                    <div class="form-group">
                        {!! Form::submit('Delete Category', ['class'=>'btn btn-danger col-md-12']) !!}
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>

        </div>
    </div>
@stop

resources/views/dashboard/sections/categories/index.blade.php
@extends('dashboard.layouts.app')

@section('title', 'D3awa/Categories')

@section('content')

    <div class=" col-md-10 float-right  col px-5 pl-md-2 pt-2 main">

        <div class="add">

            <h5>Categories</h5>

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{{route('dashboard.index')}}">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Categories</li>
                </ol>
            </nav>
        </div>
        <!-- add -->
        <div class="parent">

            <div class="row">
                <div class="col-md-6">

                    {!! Form::open(['method'=>'POST', 'action'=>'Dashboard\CategoriesController@store']) !!}
                    <div class="form-group">
                        {!! Form::label('name', 'Name:') !!}
                        {!! Form::text('name', null, ['class'=>'form-control']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::submit('Creat Category', ['class'=>'btn btn-primary']) !!}
                    </div>
                    {!! Form::close() !!}

                </div>

                <div class="col-md-6">
                    @if($categories)
                        <table class="table">
                            <thead>
                            <tr>
                                <th>id</th>
                                <th>Name</th>
                                <th>Created date</th>
                                <th>Control</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td>{{$category->id}}</td>
                                    <td>{{$category->name}}</td>
                                    <td>{{$category->created_at ? $category->created_at->diffForHumans() : 'no date'}}</td>
                                    <td>
                                        <a href="{{route('categories.edit', $category->id)}}"><i class="fa fa-pencil-square-o"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @endif
                </div>
            </div>
        </div>
    </div>
@stop